### ISSUE TITLE
doubt about vx520

### ISSUE THREAD

**Issue by davicfg** [hadialbadaoui/Vx520-JAVA-Interface#3]
Hello. I've searched on the internet how to ship a application on vx520. Do you know any thing about this topic? 
Thank you in advance.

**Comment by hadialbadaoui** [comment]
Hello,
how can I help you? 
Did you read the document well? and you have a question about it?
or you want more clarification?

Thank you, Best Regards.

**Comment by davicfg** [comment]
Yes, i've read your readme.md, but I'm ask if you know how to put a application inside the vx520.

**Comment by hadialbadaoui** [comment]
No, I can communicate with VX502. Since the Machine VX520 isn't for my company, I don't get permission to modify or add an application on it.
